export const LANG_DE_NAME = 'de';

export const LANG_DE_TRANS = {
  'subject_00': 'Systemstellenanalyse',
  'subject_01': 'Allgemeines',
  'subject_04': 'Sprach- und Literaturwissenschaften',
  'subject_07': 'Germanistik',
  'subject_10': 'Anglistik',
  'subject_13': 'Romanistik',
  'subject_16': 'sonstige Philologien',
  'subject_19': 'Philosophie',
  'subject_22': 'Psychologie',
  'subject_25': 'Erziehungswissenschaften',
  'subject_28': 'Theologie',
  'subject_31': 'Autoren GW',
  'subject_34': 'Kunstwissenschaften',
  'subject_34a': 'Medienwissenschaften',
  'subject_37': 'Sportwissenschaften',
  'subject_40': 'Geschichte',
  'subject_43': 'Geowissenschaften',
  'subject_46a': 'Sozialwissenschaften',
  'subject_46b': 'Soziologie',
  'subject_46c': 'Politikwissenschaften',
  'subject_49': 'Wirtschaftswissenschaften',
  'subject_52': 'Rechtswissenscahften',
  'subject_55': 'Land- und Forstwissenschaften',
  'subject_58': 'Naturwissenschaften',
  'subject_61': 'Mathematik',
  'subject_64': 'Informatik',
  'subject_67': 'Physik',
  'subject_70': 'Chemie',
  'subject_73': 'Astronomie',
  'subject_75': 'Biologie',
  'subject_77': 'Medizin',
  'subject_77a': 'Medizin',
  'subject_79': 'Technik allgemein',
  'subject_82': 'Bauingenieurwesen',
  'subject_85': 'Maschinenbau',
  'subject_88': 'Elektrotechnik',
  'subject_91': 'Sonstige Gebiete der Technik',
  'subject_94': 'Turkistik',
  'subject_99': 'Sonderstandorte',
  'status_deleted': 'aussondern',
  'status_ignored': 'ignorieren',
  'status_repository': 'umstellen',
  'proposed': 'Vorschlag',
  'deletion': 'Aussonderung',
  'repository': 'Magazin',
  'ignored': 'Sperren',
  'title.area': 'Angaben zum Bereich',
  'description.area': 'Dieser Abschnitt umfasst die notwendigen Angaben zum Fachbereich und der Medienart, die untersucht werden soll. Wird explizit eine Systemstelle angegeben, so erfolgt die  Analyse nur für diese. Soll die Analyse für die ganze Fachgruppe durchgeführt werden, bleibt das Feld leer. Ähnlich wie beim Ausleihprotokoll können Einschränkungen hinsichtlich der Standorte vorgenommen werden. Dabei gelten die gleichen.'
};
